------------------------------------------------------------
/Users/dougal/.virtualenvs/qengine/bin/pip run on Thu Jul 22 14:19:37 2010
Downloading/unpacking http://www.djangoproject.com/download/1.2-beta-1/tarball/ (from -r requirements.txt (line 1))
  Downloading from URL http://www.djangoproject.com/download/1.2-beta-1/tarball/
Exception:
Traceback (most recent call last):
  File "/Users/dougal/.virtualenvs/qengine/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/pip/basecommand.py", line 120, in main
    self.run(options, args)
  File "/Users/dougal/.virtualenvs/qengine/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/pip/commands/install.py", line 161, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/dougal/.virtualenvs/qengine/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/pip/req.py", line 879, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/Users/dougal/.virtualenvs/qengine/lib/python2.6/site-packages/pip-0.7.1-py2.6.egg/pip/req.py", line 1068, in unpack_url
    chunk = resp.read(4096)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/socket.py", line 351, in read
    data = self._sock.recv(left)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 537, in read
    s = self.fp.read(amt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/socket.py", line 351, in read
    data = self._sock.recv(left)
KeyboardInterrupt
